# Setup deployment for our logger
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logger
  namespace: numbat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logger
  template:
    metadata:
      labels:
        app: logger
    spec:
      containers:
      - name: logger
        image: boanlab/numbat-logger:v0.0.2
        ports:
        - containerPort: 8080
          protocol: TCP
          name: grpc
        env:
        - name: SERVER_ADDR
          value: "numbat-collector.numbat.svc.cluster.local"
        - name: SERVER_PORT
          value: "8080"
---
# Setup PV for mongodb
apiVersion: v1
kind: PersistentVolume
metadata:
    name: mongodb-pv-new
    namespace: numbat
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: mongodb-storageclass-new
  hostPath:
    path: "/home/boan/istio/mongo-data-new/"
---
# Setup PVC for mongodb
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongodb-pvc-new
  namespace: numbat
spec:
  storageClassName: mongodb-storageclass-new
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
---
# Setup deployment for mongodb
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  namespace: numbat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:latest
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-storage
              mountPath: /data/db   # This is the default data directory for MongoDB
      volumes:
        - name: mongodb-storage
          persistentVolumeClaim:
            claimName: mongodb-pvc-new
---
# Setup service for mongodb
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: numbat
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
---
# Setup deployment for our logger
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-client
  namespace: numbat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-client
  template:
    metadata:
      labels:
        app: mongo-client
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: mongo-client
        image: boanlab/numbat-mongo:v0.0.2
        env:
        - name: SERVER_ADDR
          value: "numbat-collector.numbat.svc.cluster.local"
        - name: SERVER_PORT
          value: "8080"
        - name: MONGODB_HOST
          value: "mongodb://mongo:27017"
