apiVersion: v1
kind: Namespace
metadata:
  name: kubecarto
  labels:
    istio-injection: disabled # avoid Istio sidecar-injection
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: kubecarto
  name: kubecarto-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubecarto-cr
rules:
- apiGroups: ["*"]
  verbs: ["*"]
  resources: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubecarto-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubecarto-cr
subjects:
- kind: ServiceAccount
  namespace: kubecarto
  name: kubecarto-sa
