apiVersion: apps/v1
kind: Deployment
metadata:
  name: relay-client
  namespace: sentryflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: relay-client
  template:
    metadata:
      labels:
        app: relay-client
    spec:
      containers:
      - name: relay-client
        image: 5gsec/sentryflow-relay-client:v0.1
        ports:
        - containerPort: 8080
          protocol: TCP
          name: grpc
        env:
        - name: SERVER_ADDR
          value: "sentryflow.sentryflow.svc.cluster.local"
        - name: SERVER_PORT
          value: "8080"
        - name: METRIC_FILTER
          value: "envoy"
        - name: LOG_CFG
          value: "stdout"
        - name: METRIC_CFG
          value: "stdout"
