apiVersion: v1
kind: Namespace
metadata:
  name: sentryflow
  labels:
    istio-injection: disabled # avoid Istio sidecar-injection
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: sentryflow
  name: sentryflow-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sentryflow-cr
rules:
- apiGroups: ["*"]
  verbs: ["*"]
  resources: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sentryflow-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sentryflow-cr
subjects:
- kind: ServiceAccount
  namespace: sentryflow
  name: sentryflow-sa
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: sentryflow
  name: sentryflow-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sentryflow-operator
  template:
    metadata:
      labels:
        app: sentryflow-operator
    spec:
      serviceAccountName: sentryflow-sa
      containers:
      - name: sentryflow-operator
        image: boanlab/sentryflow-operator:v0.1
        ports:
        - name: agent-grpc
          protocol: TCP
          containerPort: 5317
        - name: sentryflow-grpc
          protocol: TCP
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  namespace: sentryflow
  name: sentryflow-operator
spec:
  selector:
    app: sentryflow-operator
  ports:
  - name: agent-grpc
    protocol: TCP
    port: 5317
    targetPort: 5317
  - name: sentryflow-grpc
    protocol: TCP
    port: 8080
    targetPort: 8080
