apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: sentryflow
  name: sentryflow-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sentryflow-operator
  template:
    metadata:
      labels:
        app: sentryflow-operator
    spec:
      serviceAccountName: sentryflow-sa
      containers:
      - name: sentryflow-operator
        image: boanlab/sentryflow-operator:v0.1
        ports:
        - name: agent-grpc
          protocol: TCP
          containerPort: 5317
        - name: sentryflow-grpc
          protocol: TCP
          containerPort: 8080
