# Setup namespace for collector-1
apiVersion: v1
kind: Namespace
metadata:
  name: collector-1
---
# Setup PV for mongodb
apiVersion: v1
kind: PersistentVolume
metadata:
    name: mongodb-pv
    namespace: collector-1
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: mongodb-storageclass
  hostPath:
    path: "/home/boan/istio/mongo-data/"
---
# Setup PVC for mongodb
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongodb-pvc
spec:
  storageClassName: mongodb-storageclass
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
---
# Setup deployment for mongodb
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  namespace: collector-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:latest
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-storage
              mountPath: /data/db   # This is the default data directory for MongoDB
      volumes:
        - name: mongodb-storage
          persistentVolumeClaim:
            claimName: mongodb-pvc
---
# Setup service for mongodb
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: collector-1
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
