// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.26.0
// source: kubecarto.proto

package protobuf

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KubeCarto_GetAPILog_FullMethodName           = "/protobuf.KubeCarto/GetAPILog"
	KubeCarto_GetEnvoyMetrics_FullMethodName     = "/protobuf.KubeCarto/GetEnvoyMetrics"
	KubeCarto_AddDeployEventDB_FullMethodName    = "/protobuf.KubeCarto/AddDeployEventDB"
	KubeCarto_UpdateDeployEventDB_FullMethodName = "/protobuf.KubeCarto/UpdateDeployEventDB"
	KubeCarto_DeleteDeployEventDB_FullMethodName = "/protobuf.KubeCarto/DeleteDeployEventDB"
	KubeCarto_AddPodEventDB_FullMethodName       = "/protobuf.KubeCarto/AddPodEventDB"
	KubeCarto_UpdatePodEventDB_FullMethodName    = "/protobuf.KubeCarto/UpdatePodEventDB"
	KubeCarto_DeletePodEventDB_FullMethodName    = "/protobuf.KubeCarto/DeletePodEventDB"
	KubeCarto_AddSvcEventDB_FullMethodName       = "/protobuf.KubeCarto/AddSvcEventDB"
	KubeCarto_UpdateSvcEventDB_FullMethodName    = "/protobuf.KubeCarto/UpdateSvcEventDB"
	KubeCarto_DeleteSvcEventDB_FullMethodName    = "/protobuf.KubeCarto/DeleteSvcEventDB"
	KubeCarto_GiveAPILog_FullMethodName          = "/protobuf.KubeCarto/GiveAPILog"
	KubeCarto_GiveEnvoyMetrics_FullMethodName    = "/protobuf.KubeCarto/GiveEnvoyMetrics"
	KubeCarto_AddDeployEvent_FullMethodName      = "/protobuf.KubeCarto/AddDeployEvent"
	KubeCarto_UpdateDeployEvent_FullMethodName   = "/protobuf.KubeCarto/UpdateDeployEvent"
	KubeCarto_DeleteDeployEvent_FullMethodName   = "/protobuf.KubeCarto/DeleteDeployEvent"
	KubeCarto_AddPodEvent_FullMethodName         = "/protobuf.KubeCarto/AddPodEvent"
	KubeCarto_UpdatePodEvent_FullMethodName      = "/protobuf.KubeCarto/UpdatePodEvent"
	KubeCarto_DeletePodEvent_FullMethodName      = "/protobuf.KubeCarto/DeletePodEvent"
	KubeCarto_AddSvcEvent_FullMethodName         = "/protobuf.KubeCarto/AddSvcEvent"
	KubeCarto_UpdateSvcEvent_FullMethodName      = "/protobuf.KubeCarto/UpdateSvcEvent"
	KubeCarto_DeleteSvcEvent_FullMethodName      = "/protobuf.KubeCarto/DeleteSvcEvent"
)

// KubeCartoClient is the client API for KubeCarto service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KubeCartoClient interface {
	// manager -> client
	GetAPILog(ctx context.Context, in *ClientInfo, opts ...grpc.CallOption) (grpc.ServerStreamingClient[APILog], error)
	GetEnvoyMetrics(ctx context.Context, in *ClientInfo, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EnvoyMetrics], error)
	AddDeployEventDB(ctx context.Context, in *ClientInfo, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Deploy], error)
	UpdateDeployEventDB(ctx context.Context, in *ClientInfo, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Deploy], error)
	DeleteDeployEventDB(ctx context.Context, in *ClientInfo, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Deploy], error)
	AddPodEventDB(ctx context.Context, in *ClientInfo, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Pod], error)
	UpdatePodEventDB(ctx context.Context, in *ClientInfo, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Pod], error)
	DeletePodEventDB(ctx context.Context, in *ClientInfo, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Pod], error)
	AddSvcEventDB(ctx context.Context, in *ClientInfo, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Service], error)
	UpdateSvcEventDB(ctx context.Context, in *ClientInfo, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Service], error)
	DeleteSvcEventDB(ctx context.Context, in *ClientInfo, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Service], error)
	// agent -> manager
	GiveAPILog(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[APILog, Response], error)
	GiveEnvoyMetrics(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[EnvoyMetrics, Response], error)
	AddDeployEvent(ctx context.Context, in *Deploy, opts ...grpc.CallOption) (*Response, error)
	UpdateDeployEvent(ctx context.Context, in *Deploy, opts ...grpc.CallOption) (*Response, error)
	DeleteDeployEvent(ctx context.Context, in *Deploy, opts ...grpc.CallOption) (*Response, error)
	AddPodEvent(ctx context.Context, in *Pod, opts ...grpc.CallOption) (*Response, error)
	UpdatePodEvent(ctx context.Context, in *Pod, opts ...grpc.CallOption) (*Response, error)
	DeletePodEvent(ctx context.Context, in *Pod, opts ...grpc.CallOption) (*Response, error)
	AddSvcEvent(ctx context.Context, in *Service, opts ...grpc.CallOption) (*Response, error)
	UpdateSvcEvent(ctx context.Context, in *Service, opts ...grpc.CallOption) (*Response, error)
	DeleteSvcEvent(ctx context.Context, in *Service, opts ...grpc.CallOption) (*Response, error)
}

type kubeCartoClient struct {
	cc grpc.ClientConnInterface
}

func NewKubeCartoClient(cc grpc.ClientConnInterface) KubeCartoClient {
	return &kubeCartoClient{cc}
}

func (c *kubeCartoClient) GetAPILog(ctx context.Context, in *ClientInfo, opts ...grpc.CallOption) (grpc.ServerStreamingClient[APILog], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &KubeCarto_ServiceDesc.Streams[0], KubeCarto_GetAPILog_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ClientInfo, APILog]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KubeCarto_GetAPILogClient = grpc.ServerStreamingClient[APILog]

func (c *kubeCartoClient) GetEnvoyMetrics(ctx context.Context, in *ClientInfo, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EnvoyMetrics], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &KubeCarto_ServiceDesc.Streams[1], KubeCarto_GetEnvoyMetrics_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ClientInfo, EnvoyMetrics]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KubeCarto_GetEnvoyMetricsClient = grpc.ServerStreamingClient[EnvoyMetrics]

func (c *kubeCartoClient) AddDeployEventDB(ctx context.Context, in *ClientInfo, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Deploy], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &KubeCarto_ServiceDesc.Streams[2], KubeCarto_AddDeployEventDB_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ClientInfo, Deploy]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KubeCarto_AddDeployEventDBClient = grpc.ServerStreamingClient[Deploy]

func (c *kubeCartoClient) UpdateDeployEventDB(ctx context.Context, in *ClientInfo, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Deploy], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &KubeCarto_ServiceDesc.Streams[3], KubeCarto_UpdateDeployEventDB_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ClientInfo, Deploy]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KubeCarto_UpdateDeployEventDBClient = grpc.ServerStreamingClient[Deploy]

func (c *kubeCartoClient) DeleteDeployEventDB(ctx context.Context, in *ClientInfo, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Deploy], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &KubeCarto_ServiceDesc.Streams[4], KubeCarto_DeleteDeployEventDB_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ClientInfo, Deploy]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KubeCarto_DeleteDeployEventDBClient = grpc.ServerStreamingClient[Deploy]

func (c *kubeCartoClient) AddPodEventDB(ctx context.Context, in *ClientInfo, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Pod], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &KubeCarto_ServiceDesc.Streams[5], KubeCarto_AddPodEventDB_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ClientInfo, Pod]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KubeCarto_AddPodEventDBClient = grpc.ServerStreamingClient[Pod]

func (c *kubeCartoClient) UpdatePodEventDB(ctx context.Context, in *ClientInfo, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Pod], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &KubeCarto_ServiceDesc.Streams[6], KubeCarto_UpdatePodEventDB_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ClientInfo, Pod]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KubeCarto_UpdatePodEventDBClient = grpc.ServerStreamingClient[Pod]

func (c *kubeCartoClient) DeletePodEventDB(ctx context.Context, in *ClientInfo, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Pod], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &KubeCarto_ServiceDesc.Streams[7], KubeCarto_DeletePodEventDB_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ClientInfo, Pod]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KubeCarto_DeletePodEventDBClient = grpc.ServerStreamingClient[Pod]

func (c *kubeCartoClient) AddSvcEventDB(ctx context.Context, in *ClientInfo, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Service], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &KubeCarto_ServiceDesc.Streams[8], KubeCarto_AddSvcEventDB_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ClientInfo, Service]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KubeCarto_AddSvcEventDBClient = grpc.ServerStreamingClient[Service]

func (c *kubeCartoClient) UpdateSvcEventDB(ctx context.Context, in *ClientInfo, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Service], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &KubeCarto_ServiceDesc.Streams[9], KubeCarto_UpdateSvcEventDB_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ClientInfo, Service]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KubeCarto_UpdateSvcEventDBClient = grpc.ServerStreamingClient[Service]

func (c *kubeCartoClient) DeleteSvcEventDB(ctx context.Context, in *ClientInfo, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Service], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &KubeCarto_ServiceDesc.Streams[10], KubeCarto_DeleteSvcEventDB_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ClientInfo, Service]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KubeCarto_DeleteSvcEventDBClient = grpc.ServerStreamingClient[Service]

func (c *kubeCartoClient) GiveAPILog(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[APILog, Response], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &KubeCarto_ServiceDesc.Streams[11], KubeCarto_GiveAPILog_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[APILog, Response]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KubeCarto_GiveAPILogClient = grpc.ClientStreamingClient[APILog, Response]

func (c *kubeCartoClient) GiveEnvoyMetrics(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[EnvoyMetrics, Response], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &KubeCarto_ServiceDesc.Streams[12], KubeCarto_GiveEnvoyMetrics_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EnvoyMetrics, Response]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KubeCarto_GiveEnvoyMetricsClient = grpc.ClientStreamingClient[EnvoyMetrics, Response]

func (c *kubeCartoClient) AddDeployEvent(ctx context.Context, in *Deploy, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, KubeCarto_AddDeployEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kubeCartoClient) UpdateDeployEvent(ctx context.Context, in *Deploy, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, KubeCarto_UpdateDeployEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kubeCartoClient) DeleteDeployEvent(ctx context.Context, in *Deploy, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, KubeCarto_DeleteDeployEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kubeCartoClient) AddPodEvent(ctx context.Context, in *Pod, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, KubeCarto_AddPodEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kubeCartoClient) UpdatePodEvent(ctx context.Context, in *Pod, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, KubeCarto_UpdatePodEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kubeCartoClient) DeletePodEvent(ctx context.Context, in *Pod, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, KubeCarto_DeletePodEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kubeCartoClient) AddSvcEvent(ctx context.Context, in *Service, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, KubeCarto_AddSvcEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kubeCartoClient) UpdateSvcEvent(ctx context.Context, in *Service, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, KubeCarto_UpdateSvcEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kubeCartoClient) DeleteSvcEvent(ctx context.Context, in *Service, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, KubeCarto_DeleteSvcEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KubeCartoServer is the server API for KubeCarto service.
// All implementations should embed UnimplementedKubeCartoServer
// for forward compatibility.
type KubeCartoServer interface {
	// manager -> client
	GetAPILog(*ClientInfo, grpc.ServerStreamingServer[APILog]) error
	GetEnvoyMetrics(*ClientInfo, grpc.ServerStreamingServer[EnvoyMetrics]) error
	AddDeployEventDB(*ClientInfo, grpc.ServerStreamingServer[Deploy]) error
	UpdateDeployEventDB(*ClientInfo, grpc.ServerStreamingServer[Deploy]) error
	DeleteDeployEventDB(*ClientInfo, grpc.ServerStreamingServer[Deploy]) error
	AddPodEventDB(*ClientInfo, grpc.ServerStreamingServer[Pod]) error
	UpdatePodEventDB(*ClientInfo, grpc.ServerStreamingServer[Pod]) error
	DeletePodEventDB(*ClientInfo, grpc.ServerStreamingServer[Pod]) error
	AddSvcEventDB(*ClientInfo, grpc.ServerStreamingServer[Service]) error
	UpdateSvcEventDB(*ClientInfo, grpc.ServerStreamingServer[Service]) error
	DeleteSvcEventDB(*ClientInfo, grpc.ServerStreamingServer[Service]) error
	// agent -> manager
	GiveAPILog(grpc.ClientStreamingServer[APILog, Response]) error
	GiveEnvoyMetrics(grpc.ClientStreamingServer[EnvoyMetrics, Response]) error
	AddDeployEvent(context.Context, *Deploy) (*Response, error)
	UpdateDeployEvent(context.Context, *Deploy) (*Response, error)
	DeleteDeployEvent(context.Context, *Deploy) (*Response, error)
	AddPodEvent(context.Context, *Pod) (*Response, error)
	UpdatePodEvent(context.Context, *Pod) (*Response, error)
	DeletePodEvent(context.Context, *Pod) (*Response, error)
	AddSvcEvent(context.Context, *Service) (*Response, error)
	UpdateSvcEvent(context.Context, *Service) (*Response, error)
	DeleteSvcEvent(context.Context, *Service) (*Response, error)
}

// UnimplementedKubeCartoServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKubeCartoServer struct{}

func (UnimplementedKubeCartoServer) GetAPILog(*ClientInfo, grpc.ServerStreamingServer[APILog]) error {
	return status.Errorf(codes.Unimplemented, "method GetAPILog not implemented")
}
func (UnimplementedKubeCartoServer) GetEnvoyMetrics(*ClientInfo, grpc.ServerStreamingServer[EnvoyMetrics]) error {
	return status.Errorf(codes.Unimplemented, "method GetEnvoyMetrics not implemented")
}
func (UnimplementedKubeCartoServer) AddDeployEventDB(*ClientInfo, grpc.ServerStreamingServer[Deploy]) error {
	return status.Errorf(codes.Unimplemented, "method AddDeployEventDB not implemented")
}
func (UnimplementedKubeCartoServer) UpdateDeployEventDB(*ClientInfo, grpc.ServerStreamingServer[Deploy]) error {
	return status.Errorf(codes.Unimplemented, "method UpdateDeployEventDB not implemented")
}
func (UnimplementedKubeCartoServer) DeleteDeployEventDB(*ClientInfo, grpc.ServerStreamingServer[Deploy]) error {
	return status.Errorf(codes.Unimplemented, "method DeleteDeployEventDB not implemented")
}
func (UnimplementedKubeCartoServer) AddPodEventDB(*ClientInfo, grpc.ServerStreamingServer[Pod]) error {
	return status.Errorf(codes.Unimplemented, "method AddPodEventDB not implemented")
}
func (UnimplementedKubeCartoServer) UpdatePodEventDB(*ClientInfo, grpc.ServerStreamingServer[Pod]) error {
	return status.Errorf(codes.Unimplemented, "method UpdatePodEventDB not implemented")
}
func (UnimplementedKubeCartoServer) DeletePodEventDB(*ClientInfo, grpc.ServerStreamingServer[Pod]) error {
	return status.Errorf(codes.Unimplemented, "method DeletePodEventDB not implemented")
}
func (UnimplementedKubeCartoServer) AddSvcEventDB(*ClientInfo, grpc.ServerStreamingServer[Service]) error {
	return status.Errorf(codes.Unimplemented, "method AddSvcEventDB not implemented")
}
func (UnimplementedKubeCartoServer) UpdateSvcEventDB(*ClientInfo, grpc.ServerStreamingServer[Service]) error {
	return status.Errorf(codes.Unimplemented, "method UpdateSvcEventDB not implemented")
}
func (UnimplementedKubeCartoServer) DeleteSvcEventDB(*ClientInfo, grpc.ServerStreamingServer[Service]) error {
	return status.Errorf(codes.Unimplemented, "method DeleteSvcEventDB not implemented")
}
func (UnimplementedKubeCartoServer) GiveAPILog(grpc.ClientStreamingServer[APILog, Response]) error {
	return status.Errorf(codes.Unimplemented, "method GiveAPILog not implemented")
}
func (UnimplementedKubeCartoServer) GiveEnvoyMetrics(grpc.ClientStreamingServer[EnvoyMetrics, Response]) error {
	return status.Errorf(codes.Unimplemented, "method GiveEnvoyMetrics not implemented")
}
func (UnimplementedKubeCartoServer) AddDeployEvent(context.Context, *Deploy) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddDeployEvent not implemented")
}
func (UnimplementedKubeCartoServer) UpdateDeployEvent(context.Context, *Deploy) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDeployEvent not implemented")
}
func (UnimplementedKubeCartoServer) DeleteDeployEvent(context.Context, *Deploy) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDeployEvent not implemented")
}
func (UnimplementedKubeCartoServer) AddPodEvent(context.Context, *Pod) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddPodEvent not implemented")
}
func (UnimplementedKubeCartoServer) UpdatePodEvent(context.Context, *Pod) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePodEvent not implemented")
}
func (UnimplementedKubeCartoServer) DeletePodEvent(context.Context, *Pod) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePodEvent not implemented")
}
func (UnimplementedKubeCartoServer) AddSvcEvent(context.Context, *Service) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddSvcEvent not implemented")
}
func (UnimplementedKubeCartoServer) UpdateSvcEvent(context.Context, *Service) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSvcEvent not implemented")
}
func (UnimplementedKubeCartoServer) DeleteSvcEvent(context.Context, *Service) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSvcEvent not implemented")
}
func (UnimplementedKubeCartoServer) testEmbeddedByValue() {}

// UnsafeKubeCartoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KubeCartoServer will
// result in compilation errors.
type UnsafeKubeCartoServer interface {
	mustEmbedUnimplementedKubeCartoServer()
}

func RegisterKubeCartoServer(s grpc.ServiceRegistrar, srv KubeCartoServer) {
	// If the following call pancis, it indicates UnimplementedKubeCartoServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KubeCarto_ServiceDesc, srv)
}

func _KubeCarto_GetAPILog_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ClientInfo)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KubeCartoServer).GetAPILog(m, &grpc.GenericServerStream[ClientInfo, APILog]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KubeCarto_GetAPILogServer = grpc.ServerStreamingServer[APILog]

func _KubeCarto_GetEnvoyMetrics_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ClientInfo)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KubeCartoServer).GetEnvoyMetrics(m, &grpc.GenericServerStream[ClientInfo, EnvoyMetrics]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KubeCarto_GetEnvoyMetricsServer = grpc.ServerStreamingServer[EnvoyMetrics]

func _KubeCarto_AddDeployEventDB_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ClientInfo)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KubeCartoServer).AddDeployEventDB(m, &grpc.GenericServerStream[ClientInfo, Deploy]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KubeCarto_AddDeployEventDBServer = grpc.ServerStreamingServer[Deploy]

func _KubeCarto_UpdateDeployEventDB_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ClientInfo)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KubeCartoServer).UpdateDeployEventDB(m, &grpc.GenericServerStream[ClientInfo, Deploy]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KubeCarto_UpdateDeployEventDBServer = grpc.ServerStreamingServer[Deploy]

func _KubeCarto_DeleteDeployEventDB_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ClientInfo)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KubeCartoServer).DeleteDeployEventDB(m, &grpc.GenericServerStream[ClientInfo, Deploy]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KubeCarto_DeleteDeployEventDBServer = grpc.ServerStreamingServer[Deploy]

func _KubeCarto_AddPodEventDB_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ClientInfo)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KubeCartoServer).AddPodEventDB(m, &grpc.GenericServerStream[ClientInfo, Pod]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KubeCarto_AddPodEventDBServer = grpc.ServerStreamingServer[Pod]

func _KubeCarto_UpdatePodEventDB_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ClientInfo)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KubeCartoServer).UpdatePodEventDB(m, &grpc.GenericServerStream[ClientInfo, Pod]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KubeCarto_UpdatePodEventDBServer = grpc.ServerStreamingServer[Pod]

func _KubeCarto_DeletePodEventDB_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ClientInfo)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KubeCartoServer).DeletePodEventDB(m, &grpc.GenericServerStream[ClientInfo, Pod]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KubeCarto_DeletePodEventDBServer = grpc.ServerStreamingServer[Pod]

func _KubeCarto_AddSvcEventDB_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ClientInfo)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KubeCartoServer).AddSvcEventDB(m, &grpc.GenericServerStream[ClientInfo, Service]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KubeCarto_AddSvcEventDBServer = grpc.ServerStreamingServer[Service]

func _KubeCarto_UpdateSvcEventDB_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ClientInfo)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KubeCartoServer).UpdateSvcEventDB(m, &grpc.GenericServerStream[ClientInfo, Service]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KubeCarto_UpdateSvcEventDBServer = grpc.ServerStreamingServer[Service]

func _KubeCarto_DeleteSvcEventDB_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ClientInfo)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KubeCartoServer).DeleteSvcEventDB(m, &grpc.GenericServerStream[ClientInfo, Service]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KubeCarto_DeleteSvcEventDBServer = grpc.ServerStreamingServer[Service]

func _KubeCarto_GiveAPILog_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(KubeCartoServer).GiveAPILog(&grpc.GenericServerStream[APILog, Response]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KubeCarto_GiveAPILogServer = grpc.ClientStreamingServer[APILog, Response]

func _KubeCarto_GiveEnvoyMetrics_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(KubeCartoServer).GiveEnvoyMetrics(&grpc.GenericServerStream[EnvoyMetrics, Response]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KubeCarto_GiveEnvoyMetricsServer = grpc.ClientStreamingServer[EnvoyMetrics, Response]

func _KubeCarto_AddDeployEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Deploy)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KubeCartoServer).AddDeployEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KubeCarto_AddDeployEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KubeCartoServer).AddDeployEvent(ctx, req.(*Deploy))
	}
	return interceptor(ctx, in, info, handler)
}

func _KubeCarto_UpdateDeployEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Deploy)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KubeCartoServer).UpdateDeployEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KubeCarto_UpdateDeployEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KubeCartoServer).UpdateDeployEvent(ctx, req.(*Deploy))
	}
	return interceptor(ctx, in, info, handler)
}

func _KubeCarto_DeleteDeployEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Deploy)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KubeCartoServer).DeleteDeployEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KubeCarto_DeleteDeployEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KubeCartoServer).DeleteDeployEvent(ctx, req.(*Deploy))
	}
	return interceptor(ctx, in, info, handler)
}

func _KubeCarto_AddPodEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Pod)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KubeCartoServer).AddPodEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KubeCarto_AddPodEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KubeCartoServer).AddPodEvent(ctx, req.(*Pod))
	}
	return interceptor(ctx, in, info, handler)
}

func _KubeCarto_UpdatePodEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Pod)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KubeCartoServer).UpdatePodEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KubeCarto_UpdatePodEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KubeCartoServer).UpdatePodEvent(ctx, req.(*Pod))
	}
	return interceptor(ctx, in, info, handler)
}

func _KubeCarto_DeletePodEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Pod)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KubeCartoServer).DeletePodEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KubeCarto_DeletePodEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KubeCartoServer).DeletePodEvent(ctx, req.(*Pod))
	}
	return interceptor(ctx, in, info, handler)
}

func _KubeCarto_AddSvcEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Service)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KubeCartoServer).AddSvcEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KubeCarto_AddSvcEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KubeCartoServer).AddSvcEvent(ctx, req.(*Service))
	}
	return interceptor(ctx, in, info, handler)
}

func _KubeCarto_UpdateSvcEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Service)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KubeCartoServer).UpdateSvcEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KubeCarto_UpdateSvcEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KubeCartoServer).UpdateSvcEvent(ctx, req.(*Service))
	}
	return interceptor(ctx, in, info, handler)
}

func _KubeCarto_DeleteSvcEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Service)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KubeCartoServer).DeleteSvcEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KubeCarto_DeleteSvcEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KubeCartoServer).DeleteSvcEvent(ctx, req.(*Service))
	}
	return interceptor(ctx, in, info, handler)
}

// KubeCarto_ServiceDesc is the grpc.ServiceDesc for KubeCarto service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KubeCarto_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.KubeCarto",
	HandlerType: (*KubeCartoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddDeployEvent",
			Handler:    _KubeCarto_AddDeployEvent_Handler,
		},
		{
			MethodName: "UpdateDeployEvent",
			Handler:    _KubeCarto_UpdateDeployEvent_Handler,
		},
		{
			MethodName: "DeleteDeployEvent",
			Handler:    _KubeCarto_DeleteDeployEvent_Handler,
		},
		{
			MethodName: "AddPodEvent",
			Handler:    _KubeCarto_AddPodEvent_Handler,
		},
		{
			MethodName: "UpdatePodEvent",
			Handler:    _KubeCarto_UpdatePodEvent_Handler,
		},
		{
			MethodName: "DeletePodEvent",
			Handler:    _KubeCarto_DeletePodEvent_Handler,
		},
		{
			MethodName: "AddSvcEvent",
			Handler:    _KubeCarto_AddSvcEvent_Handler,
		},
		{
			MethodName: "UpdateSvcEvent",
			Handler:    _KubeCarto_UpdateSvcEvent_Handler,
		},
		{
			MethodName: "DeleteSvcEvent",
			Handler:    _KubeCarto_DeleteSvcEvent_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetAPILog",
			Handler:       _KubeCarto_GetAPILog_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetEnvoyMetrics",
			Handler:       _KubeCarto_GetEnvoyMetrics_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "AddDeployEventDB",
			Handler:       _KubeCarto_AddDeployEventDB_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "UpdateDeployEventDB",
			Handler:       _KubeCarto_UpdateDeployEventDB_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "DeleteDeployEventDB",
			Handler:       _KubeCarto_DeleteDeployEventDB_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "AddPodEventDB",
			Handler:       _KubeCarto_AddPodEventDB_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "UpdatePodEventDB",
			Handler:       _KubeCarto_UpdatePodEventDB_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "DeletePodEventDB",
			Handler:       _KubeCarto_DeletePodEventDB_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "AddSvcEventDB",
			Handler:       _KubeCarto_AddSvcEventDB_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "UpdateSvcEventDB",
			Handler:       _KubeCarto_UpdateSvcEventDB_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "DeleteSvcEventDB",
			Handler:       _KubeCarto_DeleteSvcEventDB_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GiveAPILog",
			Handler:       _KubeCarto_GiveAPILog_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "GiveEnvoyMetrics",
			Handler:       _KubeCarto_GiveEnvoyMetrics_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "kubecarto.proto",
}
