# Setup namespace for collector-2
# This is when using native collector
# : otel/opentelemetry-collector-contrib + our custom exporter!
apiVersion: v1
kind: Namespace
metadata:
  name: collector-2

---
# Setup deployment for our custom-collector
apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-collector
  namespace: collector-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custom-collector
  template:
    metadata:
      labels:
        app: custom-collector
    spec:
      containers:
      - name: custom-collector
        image: boanlab.com/custom-exporter:v1
        ports:
        - containerPort: 4317
          protocol: TCP
          name: grpc-otlp
        env:
        - name: LISTEN_ADDR
          value: "0.0.0.0"
        - name: LISTEN_PORT
          value: "4317"
---
# Setup service for custom-collector
apiVersion: v1
kind: Service
metadata:
  name: custom-collector
  namespace: collector-2
spec:
  selector:
    app: custom-collector
  ports:
    - protocol: TCP
      port: 4317
      targetPort: 4317
      name: grpc-otlp
