# Setup namespace for collector-1
# This is when using native collector
# : otel/opentelemetry-collector-contrib + our custom exporter!
apiVersion: v1
kind: Namespace
metadata:
  name: collector-1
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-boan
  namespace: collector-1
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cr-boan
rules:
- apiGroups: ["*"]
  verbs: ["*"]
  resources: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rb-boan
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cr-boan
subjects:
- kind: ServiceAccount
  name: sa-boan
  namespace: collector-1
---
# Setup configmap for otel collector
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-config
  namespace: collector-1
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:

    processors:
      batch:

    exporters:
      #logging:
        #loglevel: debug
      otlp:
        endpoint: custom-collector:4317
        tls:
          insecure: true

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch] # what else?
          exporters:
            - otlp
            #- logging
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters:
            - otlp
            #- logging
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters:
            - otlp
            #- logging
---
# Setup deployment for our custom-exporter
apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-collector
  namespace: collector-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custom-collector
  template:
    metadata:
      labels:
        app: custom-collector
    spec:
      serviceAccountName: sa-boan
      containers:
      - name: custom-collector
        image: boanlab.com/custom-collector:v1
        ports:
        - containerPort: 4317
          protocol: TCP
          name: grpc-otlp
        env:
        - name: LISTEN_ADDR
          value: "0.0.0.0"
        - name: LISTEN_PORT
          value: "4317"
---
# Setup service for custom-exporter
apiVersion: v1
kind: Service
metadata:
  name: custom-collector
  namespace: collector-1
spec:
  selector:
    app: custom-collector
  ports:
    - protocol: TCP
      port: 4317
      targetPort: 4317
      name: grpc-otlp
