name: Numbat Go Build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v3
      with:
          go-version: 1.19

    - name: Build Go
      working-directory: ./numbat  # todo: change according to the file structures in the future
      run: |
        go get
        go build
