name: Numbat Code Style Check

on:
  pull_request:
    branches:
      - main
    
jobs:
  style-check:
    name: Check Golang code style using Golint for Numbat
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Run golangci-lint for Numbat
        working-directory: ./numbat  # todo: change according to the file structures in the future
        run: |
          go get -u ./...
          golangci-lint run